##  [ 2025년 데이터분석경진대회 범죄율 데이터 시각화]
##  - 데이터제공 : crime.csv

## 1. 필요 라이브러리 선언

In [2]:
import pandas as pd  
import numpy as np  #연산
import seaborn as sns  #시각화
import matplotlib as mpl #시각화
import matplotlib.pyplot as plt  #차트 플롯
import matplotlib.font_manager as fm  #폰트 설정

## 2. 폰트 설정

In [3]:
# 폰트 설정
mpl.rc('font', family='Malgun Gothic') # 맑은고딕으로 폰트 지정
plt.rcParams['axes.unicode_minus'] = False # 마이너스 기호 깨짐 방지

## 3. 데이터 불러오기  [ col 어떤 것이 있는지 확인하기 ]

In [5]:
df1 = pd.read_csv('crime.csv', encoding="cp949")
df1

,범죄대분류,범죄중분류,아파트-연립다세대,단독주택,고속도로,노상,백화점,슈퍼마켓,편의점,대형할인매장,...,종교기관,산야,해상,부대,구금장소,공지,주차장,공중화장실,피씨방,기타
0,강력범죄,살인기수,111,80,0,42,0,0,0,0,...,3,5,0,0,0,1,2,1,0,20
1,강력범죄,살인미수등,99,92,0,96,0,1,1,1,...,1,2,3,0,0,0,11,1,0,28
2,강력범죄,강도,77,54,1,164,1,17,68,1,...,1,4,0,0,0,0,19,0,3,34
3,강력범죄,강간,1516,958,3,157,0,0,5,0,...,10,12,1,0,0,0,37,44,3,299
4,강력범죄,유사강간,229,131,0,43,0,0,3,0,...,2,1,0,1,2,0,7,8,0,64
5,강력범죄,강제추행,1492,1012,7,2772,25,101,283,14,...,43,21,6,17,11,1,121,76,53,1158
6,강력범죄,기타 강간-강제추행등,77,64,0,15,0,0,1,0,...,0,1,0,0,0,0,3,4,0,16
7,강력범죄,방화,291,319,0,181,2,3,3,0,...,13,13,2,0,0,0,33,9,2,75
8,절도범죄,절도범죄,16697,10196,161,46861,2695,9273,5944,3065,...,605,3536,94,12,4,58,10661,887,2051,11576
9,폭력범죄,상해,4657,3240,55,11451,20,108,184,13,...,73,158,23,2,11,9,747,60,78,1926
10,폭력범죄,폭행,23335,13417,184,51704,108,597,1542,102,...,176,243,84,51,24,8,3148,244,393,7881
11,폭력범죄,체포-감금,210,132,6,244,2,1,4,0,...,7,2,0,1,0,0,19,1,3,112
12,폭력범죄,협박,4511,3192,106,6526,11,75,241,11,...,45,64,11,6,5,0,254,4,39,2679
13,폭력범죄,약취-유인,38,23,0,78,0,0,1,0,...,0,0,0,0,0,0,2,0,0,26
14,폭력범죄,폭력행위등,565,344,5,3401,2,11,26,1,...,32,57,3,6,1,2,219,21,15,554
15,폭력범죄,공갈,309,387,1,665,5,11,84,1,...,7,4,0,4,0,0,36,5,47,2897
16,폭력범죄,손괴,7567,4573,37,22936,24,127,286,27,...,161,1425,93,3,2,25,7765,139,153,3544
17,지능범죄,직무유기,4,8,1,65,0,0,0,0,...,0,9,0,2,5,1,2,0,0,193
18,지능범죄,직권남용,11,12,0,83,0,1,1,0,...,2,2,1,1,9,0,4,0,0,182
19,지능범죄,증수뢰,0,5,0,13,0,1,0,0,...,0,1,0,2,0,0,4,0,0,74
20,지능범죄,통화,2,3,2,29,1,22,19,0,...,0,0,0,0,0,0,0,0,0,97
21,지능범죄,문서-인장,307,289,10,689,1,20,192,9,...,19,21,50,10,3,1,86,0,17,4401
22,지능범죄,유가증권인지,1,0,0,5,0,1,1,0,...,0,0,0,0,0,0,0,0,0,27
23,지능범죄,사기,12365,18366,1161,36460,145,395,1266,71,...,194,393,75,47,13,16,821,2,402,191781
24,지능범죄,횡령,1991,1035,151,22669,253,641,989,214,...,72,130,57,3,0,8,930,1076,236,9606
25,지능범죄,배임,175,79,0,192,6,5,4,4,...,19,23,1,1,0,3,4,0,6,1439
26,풍속범죄,성풍속범죄,1555,1156,5,2182,30,61,100,24,...,6,14,0,8,0,3,47,1025,91,4902
27,풍속범죄,도박범죄,329,794,0,105,0,6,2,0,...,1,19,2,16,0,0,5,0,155,3653
28,특별경제범죄,특별경제범죄,1471,1068,31,4856,38,500,1424,59,...,82,117,11,2,0,4,216,2,127,14353
29,마약범죄,마약범죄,883,1982,5,1771,4,4,52,0,...,3,336,0,1,0,4,104,31,11,1645
30,보건범죄,보건범죄,1083,638,3,983,4,75,41,5,...,76,60,287,0,0,2,22,0,64,3267
31,환경범죄,환경범죄,11,14,2,589,0,6,0,0,...,0,305,389,2,0,10,7,0,0,942
32,교통범죄,교통범죄,114,45,4154,342058,0,1,4,1,...,3,49,119,3,0,4,826,0,0,980
33,노동범죄,노동범죄,8,8,0,23,0,0,1,0,...,1,2,14,0,1,0,0,0,0,106
34,안보범죄,안보범죄,3,7,0,42,0,0,0,0,...,1,0,0,0,0,0,0,0,0,99
35,선거범죄,선거범죄,17,19,0,264,0,0,0,0,...,35,0,0,0,0,0,4,0,0,215
36,병역범죄,병역범죄,345,672,0,148,0,0,0,0,...,0,0,1,401,0,3,0,0,0,1808
37,기타범죄,기타범죄,17930,15522,1267,43020,94,687,1925,68,...,566,2842,24156,131,28,90,1673,212,1361,72740

## 4. col에 어떤 것이 있는지 출력

In [6]:
df1.columns

Index(['범죄대분류', '범죄중분류', '아파트-연립다세대', '단독주택', '고속도로', '노상', '백화점', '슈퍼마켓',
       '편의점', '대형할인매장', '상점', '시장-노점', '숙박업소-목욕탕', '유흥접객업소', '사무실', '공장',
       '공사장-광산', '창고', '역-대합실', '지하철', '기타표통수단내', '흥행장', '유원지', '학교', '금융기관',
       '의료기관', '종교기관', '산야', '해상', '부대', '구금장소', '공지', '주차장', '공중화장실', '피씨방',
       '기타'],
      dtype='object')

## 5. '범죄대분류'만 다시 unique

In [7]:
df1['범죄대분류'].unique()

array(['강력범죄', '절도범죄', '폭력범죄', '지능범죄', '풍속범죄', '특별경제범죄', '마약범죄', '보건범죄',
       '환경범죄', '교통범죄', '노동범죄', '안보범죄', '선거범죄', '병역범죄', '기타범죄'],
      dtype=object)

## 6. 범죄대분류 최대 빈도수 분석 [ 그룹화 : groupby ]

In [8]:
df1.groupby('범죄대분류').count()

,범죄중분류,아파트-연립다세대,단독주택,고속도로,노상,백화점,슈퍼마켓,편의점,대형할인매장,상점,...,종교기관,산야,해상,부대,구금장소,공지,주차장,공중화장실,피씨방,기타
범죄대분류,,,,,,,,,,,,,,,,,,,,,
강력범죄,8,8,8,8,8,8,8,8,8,8,...,8,8,8,8,8,8,8,8,8,8
교통범죄,1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
기타범죄,1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
노동범죄,1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
마약범죄,1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
병역범죄,1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
보건범죄,1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
선거범죄,1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
안보범죄,1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
절도범죄,1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
지능범죄,9,9,9,9,9,9,9,9,9,9,...,9,9,9,9,9,9,9,9,9,9
특별경제범죄,1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1
폭력범죄,8,8,8,8,8,8,8,8,8,8,...,8,8,8,8,8,8,8,8,8,8
풍속범죄,2,2,2,2,2,2,2,2,2,2,...,2,2,2,2,2,2,2,2,2,2
환경범죄,1,1,1,1,1,1,1,1,1,1,...,1,1,1,1,1,1,1,1,1,1

## 7. 범죄대분류별 합계 sum

## 8. 범죄대분류별 합계 및 내림차순
### [ 인덱스(index) 재설정 ] [ col 이름 변경 ]

# 9. 최대 빈도수의 범죄대분류 리스트 생성

## 10. 막대 그래프 시각화 [ 상위 5개 출력 ]

## 11. '지능범죄' 중 범죄중분류 최대 빈도수 분석

## 12. '교통범죄' 중 범죄중분류 최대 빈도수 분석

## 13. '폭력범죄' 중 범죄중분류 최대 빈도수 분석

## 14. '기타범죄' 중 범죄중분류 최대 빈도수 분석

## 15. '절도범죄' 중 범죄중분류 최대 빈도수 분석